### PR TITLE
Akshay apte

### PR DESCRIPTION
**Pull request by akshayapte5**
added follow-up examination form in addpatient.html with radio buttons.

### CODE REVIEW

**Comment by purveshmakode24** [comment]
Including --> {#     Akshay's code begins for followup form for which no one , I repeat, no one provided me information about.      #} doesn't beautify your unaligned code.

**Comment by akshayapte5** [comment]
> 
> 
> Including --> {# Akshay's code begins for followup form for which no one , I repeat, no one provided me information about. #} doesn't beautify your unaligned code, buddy!

**Comment by akshayapte5** [comment]
> Including --> {# Akshay's code begins for followup form for which no one , I repeat, no one provided me information about. #} doesn't beautify your unaligned code, buddy!

bhai usse nahi kiya lol lmao , beautiful code means nothing if it doen't work

**Comment by akshayapte5** [comment]
> unaligned code

And code is very much aligned **buddy**, fix Yo eyes

**Comment by purveshmakode24** [comment]
> beautiful code means nothing if it doen't work

nothing's fixed buddy, check it out one more time. There is unnecessary spacing between the tags.

**Comment by akshayapte5** [comment]
Must be a problem with your 30 min free software

**Pull request closed without merging**
